services:
  backroomsgraph:
    image: mfauzanrizkyagusta/backroomsgraph:1.1.0
    container_name: backroomsgraph
    depends_on:
      - db
      - chrome
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
      SELENIUM_REMOTE_URL: ${SELENIUM_REMOTE_URL}
    restart: unless-stopped
  chrome:
    image: selenium/standalone-chrome:latest
  db:
    image: postgres:15-alpine
    container_name: backroomsgraph_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  postgres_data: